### ISSUE TITLE
How to combine speechrecognition and recording?

### ISSUE THREAD

**Issue by URadermacher** [nuecho/rivr-cookbook#2]
The Interaction.Builder has only methods build() with as first parameter  a SpeechRecognition or a DtmfRecognitions or a Recording. To do a quality check on our grammar I would like to get a recording of the utterances used to do speech recognition. I.e. I would like to record the very sound that is used for speechrecognition. How can I accomplish this with rivr?

**Comment by gawi** [comment]
If your platform is compliant with VoiceXML 2.1, you need to set the `recordutterance` property to `true` before performing a speech-recognition interaction. This can be achieved like this:

    context.getProperties().put("recordutterance", "true");

Note that the property will be set for the rest of the dialogue, so don't forget to remove it once your done.

To retrieve the recording, use the `getRecordingInfo()` method of the `VoiceXmlInputTurn` class.

See http://www.w3.org/TR/voicexml21/#sec-reco_reco

**Comment by URadermacher** [comment]
Yeah, thanks.. I tried 
" speechRecognition.addProperty("recordutterance","true");"
which changed the normal POST to a POST of a multipart message. So I expected a file as one of the parts, but I hit a bug(?) in VoiceXmlInputTurnFactory.findEncoding():
The content type is "text/plain; charset=UTF-8"  but the matcher  returns "U" as encoding name, which is rejected as an encoding in the CTOR of String(bytes,encoding):
"java.io.UnsupportedEncodingException: U"

**Comment by URadermacher** [comment]
A test class
'public class TT {

    private static final Pattern CHAR_SET_PATTERN = Pattern.compile("charset\\s*=\\s*([^ ;])");

	public static void main(String[] args) {
		TT tt = new TT();
		tt.doit();
	}

	
	private void doit(){
		String contentType = "text/plain; charset=UTF-8;";
		 Matcher matcher = CHAR_SET_PATTERN.matcher(contentType);
		 String encoding = "unklnown";
		 if (matcher.find()) {
		                 encoding = matcher.group(1);
		  } else {
		               encoding = Encoding.UTF_8.getId();
		  }
		 System.out.println("Encoding = " + encoding);
	}
}
'

**Comment by gawi** [comment]
1) You are so right about `Recognition.addProperty()`. That's the correct pattern for interaction-volatile properties. I forgot about it.
2) Yes, I confirm there is a bug about charset extraction from the Content-Type header.  I found the bug a few weeks ago. I have a fix for it and I'll try to publish new Rivr version tomorrow. If you can't wait and if you're able to build Rivr yourself, you may try this quick fix:

    Pattern.compile("charset\\s*=\\s*([^ ;]+)");

**Comment by URadermacher** [comment]
Thanks a lot, this does the trick!

**Comment by gawi** [comment]
Rivr 1.0.6 has been released with this fix.
Thanks!
